product_index:
    path:     /
    defaults: { _controller: "EspritBaseBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "EspritBaseBundle:Product:show" }
    methods:  [GET, POST]

product_new:
    path:     /new
    defaults: { _controller: "EspritBaseBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "EspritBaseBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "EspritBaseBundle:Product:delete" }
    methods:  DELETE

rating_product:
    path:     /{id}/ratingProduct
    defaults: { _controller: "EspritBaseBundle:Product:ratingProduct" }

chart:
    path:     /chart
    defaults: { _controller: "EspritBaseBundle:Product:chart" }